# QNO1

In [3]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
import numpy as np
data = np.arange(60)
tensor = np.ones((3, 4, 5))
print(tensor)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [6]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
even_nums = data[data % 2 == 0]
print(even_nums)


[2 4 6 8]


In [7]:
a = np.array([np.arange(i,i + 5) for i in range(10, 60, 10)])
a

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [50, 51, 52, 53, 54]])

In [8]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


# QNO2

In [9]:

arr4 = np.array([[10, 20, 30, 40, 50],
                  [60, 70, 80, 90, 100],
                  [110, 120, 130, 140, 150],
                  [160, 170, 180, 190, 200],
                  [210, 220, 230, 240, 250]])
data = arr4[:, :]
data


array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [10]:
arr5 = np.array([[75.2,78.3,81.5,79.0,82.1],
                 [71.6,73.8,77.4,79.8,84.1],
                 [73.2,75.1,76.8,78.9,82.5],
                 [75.0,77.0,79.0,81.0,83.0],
                 [76.4,79.3,81.2,82.1,84.5]])
data = arr5[:, :]
data

array([[75.2, 78.3, 81.5, 79. , 82.1],
       [71.6, 73.8, 77.4, 79.8, 84.1],
       [73.2, 75.1, 76.8, 78.9, 82.5],
       [75. , 77. , 79. , 81. , 83. ],
       [76.4, 79.3, 81.2, 82.1, 84.5]])

In [11]:
arr6 = np.array([[50.2,53.3,56.5,59.0,62.1],
                 [62.1,62.8,63.4,63.8,64.1],
                 [71.1,71.2,71.3,71.4,71.5]])
data = arr6[:, :]
data 


array([[50.2, 53.3, 56.5, 59. , 62.1],
       [62.1, 62.8, 63.4, 63.8, 64.1],
       [71.1, 71.2, 71.3, 71.4, 71.5]])

In [12]:
arr7 = np.array([[85,92,78],
                 [75,72,84],
                 [80,81,86],
                 [77,90,81]])
data = arr7[:, :]
data

array([[85, 92, 78],
       [75, 72, 84],
       [80, 81, 86],
       [77, 90, 81]])

# QNO3

In [13]:
import numpy as np

# Define the 3D array
cube = np.array([[[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20]],
                 
                 [[21, 22, 23, 24, 25],
                  [26, 27, 28, 29, 30],
                  [31, 32, 33, 34, 35],
                  [36, 37, 38, 39, 40]],
                 
                 [[41, 42, 43, 44, 45],
                  [46, 47, 48, 49, 50],
                  [51, 52, 53, 54, 55],
                  [56, 57, 58, 59, 60]]])




In [16]:
element = cube[2, 3, 4]
print(" (2, 3, 4):", element)

 (2, 3, 4): 60


In [17]:
second_2d_array = cube[1, :, :]
print( second_2d_array)


[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [18]:
first_row = cube[1, 0, :]
print( first_row)

[21 22 23 24 25]


In [19]:
sub_matrix = cube[2, 1:3, 1:4]
print( sub_matrix)

[[47 48 49]
 [52 53 54]]


In [22]:
import numpy as np

# Define the 3D array
data_cube = np.array([[[10, 20, 30],
                       [40, 50, 60],
                       [70, 80, 90]],
                      
                      [[110, 120, 130],
                       [140, 150, 160],
                       [170, 180, 190]],
                      
                      [[210, 220, 230],
                       [240, 250, 260],
                       [270, 280, 290]],
                      
                      [[310, 320, 330],
                       [340, 350, 360],
                       [370, 380, 390]]])

# Extract the element at coordinates 2, 1, 2.
element = data_cube[2, 1, 2]
print("Element at coordinates (2, 1, 2):", element)

# Extract the entire 2D array at depth 3.
depth_3_array = data_cube[3, :, :]
print("2D array at depth 3:\n", depth_3_array)

# Extract the last column of the first 2D array at depth 1.
last_column = data_cube[1, :, -1]
print("Last column of the first 2D array at depth 1:", last_column)

# Extract a 2x2 sub-matrix from the third 2D array at depth 2 starting from the coordinates (0, 1).
sub_matrix = data_cube[2, 1:3, 0:2]
print("2x2 sub-matrix from the third 2D array at depth 2 starting from (0, 1):\n", sub_matrix)

Element at coordinates (2, 1, 2): 260
2D array at depth 3:
 [[310 320 330]
 [340 350 360]
 [370 380 390]]
Last column of the first 2D array at depth 1: [130 160 190]
2x2 sub-matrix from the third 2D array at depth 2 starting from (0, 1):
 [[240 250]
 [270 280]]


In [58]:
import numpy as np

# Define the 3D array
color_cube = np.array([[[255, 0, 0],
                        [0, 255, 0],
                        [0, 0, 255]],
                       
                       [[128, 128, 0],
                        [0, 128, 128],
                        [128, 0, 128]]])

# Extract the RGB value at coordinates (1, 2, 3)
rgb_value = color_cube[1, 2, 1]
print("RGB value at coordinates (1, 2, 3):", rgb_value)




RGB value at coordinates (1, 2, 3): 0


In [59]:
# Extract the entire 2D array at depth 1
depth_1_array = color_cube[1, :, :]
print("2D array at depth 1:\n", depth_1_array)


2D array at depth 1:
 [[128 128   0]
 [  0 128 128]
 [128   0 128]]


In [60]:

# Extract the green channel (middle value) from the 2D array at depth 0
green_channel = color_cube[0, :, 1]
print("Green channel from the 2D array at depth 0:", green_channel)

Green channel from the 2D array at depth 0: [  0 255   0]


In [61]:
# Extract a 2x2 sub-matrix from the first 2D array at depth 0 starting from the coordinates (0, 1)
sub_matrix = color_cube[0, 1:3, 0:2]
print("2x2 sub-matrix from the first 2D array at depth 0 starting from (0, 1):\n", sub_matrix)

2x2 sub-matrix from the first 2D array at depth 0 starting from (0, 1):
 [[  0 255]
 [  0   0]]


# QNO4

In [63]:
import numpy as np

# Define the 2D array
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

# a) Find all elements in the 2D array matrix that are greater than 8.
greater_than_8 = matrix[matrix > 8]
print("Elements greater than 8:", greater_than_8)

# b) Extract a sub-array from the 2D array matrix containing all elements that are divisible by 3.
divisible_by_3 = matrix[matrix % 3 == 0]
print("Elements divisible by 3:", divisible_by_3)


Elements greater than 8: [ 9 10 11 12 13 14 15 16]
Elements divisible by 3: [ 3  6  9 12 15]


In [64]:
import numpy as np

# Define the 3D array
data_cube = np.array([[[10, 20, 30],
                       [40, 50, 60],
                       [70, 80, 90]],
                      
                      [[110, 120, 130],
                       [140, 150, 160],
                       [170, 180, 190]],
                      
                      [[210, 220, 230],
                       [240, 250, 260],
                       [270, 280, 290]],
                      
                      [[310, 320, 330],
                       [340, 350, 360],
                       [370, 380, 390]]])

# a) Find all elements in the 3D array data cube that are greater than 100.
greater_than_100 = data_cube[data_cube > 100]
print("Elements greater than 100:", greater_than_100)

# b) Extract a sub-array from the 3D array data cube containing all elements that are divisible by 20.
divisible_by_20 = data_cube[data_cube % 20 == 0]
print("Elements divisible by 20:", divisible_by_20)

# c) Create a boolean mask for elements in the 3D array data cube greater than 250 and less than 350, and then use the mask to extract the corresponding elements.
mask = (data_cube > 250) & (data_cube < 350)
elements_between_250_and_350 = data_cube[mask]
print("Elements between 250 and 350:", elements_between_250_and_350)


Elements greater than 100: [110 120 130 140 150 160 170 180 190 210 220 230 240 250 260 270 280 290
 310 320 330 340 350 360 370 380 390]
Elements divisible by 20: [ 20  40  60  80 120 140 160 180 220 240 260 280 320 340 360 380]
Elements between 250 and 350: [260 270 280 290 310 320 330 340]


# QNO5

In [65]:
import numpy as np

# Define the arrays
array1 = np.array([10, 20, 30, 40])
array2 = np.array([5])

# 1. Perform an addition operation using broadcasting to add array2 to array1.
addition_result = array1 + array2
print("Addition result:", addition_result)

# 2. Perform a multiplication operation using broadcasting to multiply array1 by array2.
multiplication_result = array1 * array2
print("Multiplication result:", multiplication_result)

# 3. Create a new NumPy array, array3, that is a result of adding a scalar value of 15 to array1 using broadcasting.
scalar_value = 15
array3 = array1 + scalar_value
print("Array3:", array3)

# 4. Create a new NumPy array, array4, that is a result of multiplying array1 by a scalar value of 3 using broadcasting.
scalar_value = 3
array4 = array1 * scalar_value
print("Array4:", array4)

# 5. Perform a subtraction operation using broadcasting to subtract array2 from array1.
subtraction_result = array1 - array2
print("Subtraction result:", subtraction_result)


Addition result: [15 25 35 45]
Multiplication result: [ 50 100 150 200]
Array3: [25 35 45 55]
Array4: [ 30  60  90 120]
Subtraction result: [ 5 15 25 35]


In [66]:
import numpy as np

# Define the arrays
matrix1 = np.array([[1, 2], [3, 4], [5, 6]])
array3 = np.array([10, 20])

# 1. Perform an addition operation using broadcasting to add array3 to matrix1.
addition_result = matrix1 + array3.reshape(1, -1)
print("Addition result:", addition_result)

# 2. Perform a multiplication operation using broadcasting to multiply each column of matrix1 by array3.
multiplication_result = matrix1 * array3.reshape(1, -1)
print("Multiplication result:", multiplication_result)

# 3. Create a new NumPy array, matrix2, that is a result of adding a scalar value of 5 to matrix1 using broadcasting.
scalar_value = 5
matrix2 = matrix1 + scalar_value
print("Matrix2:", matrix2)

# 4. Create a new NumPy array, matrix3, that is a result of multiplying matrix1 by a scalar value of 2 using broadcasting.
scalar_value = 2
matrix3 = matrix1 * scalar_value
print("Matrix3:", matrix3)

# 5. Perform a division operation using broadcasting to divide each element of matrix1 by the corresponding element of array3.
division_result = matrix1 / array3.reshape(1, -1)
print("Division result:", division_result)


Addition result: [[11 22]
 [13 24]
 [15 26]]
Multiplication result: [[ 10  40]
 [ 30  80]
 [ 50 120]]
Matrix2: [[ 6  7]
 [ 8  9]
 [10 11]]
Matrix3: [[ 2  4]
 [ 6  8]
 [10 12]]
Division result: [[0.1 0.1]
 [0.3 0.2]
 [0.5 0.3]]
